/*
 * Additional catalogues for Evidenta: ISO 9001:2026, NIS2 (Directive (EU) 2022/2555), TISAX (VDA ISA 6, Information Security module).
 * Only reference numbers and SCE Assurance's own short Bosnian descriptions.
 * The text of ISO standards and of the VDA ISA catalogue is copyrighted and is NOT reproduced here.
 */

/* ---------- ISO 9001:2026 ---------- */
const Q = (id, title, hint) => ({ id: "q" + id, code: id, kind: "clause", group: id.split(".")[0], title, hint });
export const ISO9001 = [
  Q("4.1", "Organizacija i njen kontekst", "Unutrašnja i vanjska pitanja važna za svrhu i strategiju, uključujući uticaj klimatskih promjena."),
  Q("4.2", "Zainteresovane strane", "Ko su zainteresovane strane, šta traže i koji njihovi zahtjevi ulaze u QMS."),
  Q("4.3", "Obim sistema upravljanja kvalitetom", "Lokacije, proizvodi i usluge u obimu; obrazloženje ako se neki zahtjev ne primjenjuje."),
  Q("4.4", "QMS i njegovi procesi", "Mapa procesa, ulazi i izlazi, vlasnici, kriteriji i pokazatelji procesa."),
  Q("5.1.1", "Liderstvo, kultura kvaliteta i etika", "Uprava preuzima odgovornost za QMS i aktivno promoviše kulturu kvaliteta i etično ponašanje (novo u verziji 2026)."),
  Q("5.1.2", "Fokus na kupca", "Zahtjevi kupaca i zakona se određuju i ispunjavaju; zadovoljstvo kupaca je cilj."),
  Q("5.2.1", "Uspostava politike kvaliteta", "Politika usklađena sa svrhom, kontekstom i strateškim pravcem organizacije."),
  Q("5.2.2", "Komuniciranje politike kvaliteta", "Politika je dokumentovana, poznata zaposlenima i dostupna zainteresovanim stranama."),
  Q("5.3", "Uloge, odgovornosti i ovlaštenja", "Ko je odgovoran za QMS, izvještavanje upravi i integritet sistema pri promjenama."),
  Q("6.1.1", "Rizici i prilike: opšte", "Određivanje rizika i prilika iz konteksta i zahtjeva zainteresovanih strana."),
  Q("6.1.2", "Mjere za rizike", "Planirane mjere za rizike, proporcionalne uticaju, i provjera njihove efikasnosti (odvojeno u verziji 2026)."),
  Q("6.1.3", "Mjere za prilike", "Planirane mjere za iskorištavanje prilika (novo, odvojeno od rizika u verziji 2026)."),
  Q("6.2", "Ciljevi kvaliteta i planiranje", "Mjerljivi ciljevi, ko, šta, do kada i kako se prati."),
  Q("6.3", "Planiranje promjena", "Promjene QMS-a se planiraju: svrha, posljedice, resursi, odgovornosti; praćenje nakon promjene."),
  Q("7.1.1", "Resursi: opšte", "Potrebni unutrašnji i vanjski resursi za QMS."),
  Q("7.1.2", "Ljudi", "Dovoljno ljudi za rad procesa i QMS-a."),
  Q("7.1.3", "Infrastruktura", "Zgrade, oprema, IT i transport potrebni za procese, uz održavanje."),
  Q("7.1.4", "Okruženje za rad procesa", "Fizički, socijalni i psihološki uslovi potrebni za usaglašenost proizvoda i usluga."),
  Q("7.1.5", "Resursi za praćenje i mjerenje", "Mjerna oprema odgovara namjeni, kalibracija i sljedivost mjerenja."),
  Q("7.1.6", "Znanje organizacije", "Znanje potrebno za procese se čuva, dijeli i dopunjuje."),
  Q("7.2", "Kompetentnost", "Potrebne kompetencije, obuke, ocjena efikasnosti i zapisi."),
  Q("7.3", "Svijest", "Zaposleni znaju politiku, ciljeve, svoj doprinos, kulturu kvaliteta i posljedice neusaglašenosti."),
  Q("7.4", "Komunikacija", "Šta, kada, kome, kako i ko komunicira unutar i izvan organizacije."),
  Q("7.5.1", "Dokumentovane informacije: opšte", "Dokumenti koje traži standard i oni potrebni za efikasan QMS."),
  Q("7.5.2", "Kreiranje i ažuriranje", "Označavanje, format, preispitivanje i odobravanje dokumenata."),
  Q("7.5.3", "Kontrola dokumentovanih informacija", "Dostupnost, zaštita, verzije, čuvanje i uklanjanje zastarjelih dokumenata."),
  Q("8.1", "Operativno planiranje i kontrola", "Planiranje procesa za proizvode i usluge, kriteriji prihvatanja, kontrola promjena i eksternalizovanih procesa."),
  Q("8.2.1", "Komunikacija s kupcima", "Informacije o proizvodima, upiti, ugovori, povratne informacije i reklamacije."),
  Q("8.2.2", "Određivanje zahtjeva", "Zahtjevi kupca, zakonski zahtjevi i zahtjevi koje organizacija smatra potrebnim."),
  Q("8.2.3", "Preispitivanje zahtjeva", "Prije prihvatanja narudžbe: možemo li ispuniti zahtjeve; zapisi o preispitivanju."),
  Q("8.2.4", "Promjene zahtjeva", "Izmjene narudžbi se dokumentuju i komuniciraju svima koji trebaju znati."),
  Q("8.3.1", "Projektovanje i razvoj: opšte", "Proces razvoja uspostavljen ako organizacija projektuje proizvode ili usluge."),
  Q("8.3.2", "Planiranje razvoja", "Faze, preispitivanja, verifikacija, validacija, odgovornosti i resursi."),
  Q("8.3.3", "Ulazi za razvoj", "Funkcionalni zahtjevi, zakoni, standardi, iskustva iz ranijih projekata."),
  Q("8.3.4", "Kontrole razvoja", "Preispitivanja, verifikacija i validacija s dokumentovanim rezultatima."),
  Q("8.3.5", "Izlazi iz razvoja", "Izlazi ispunjavaju ulaze i sadrže kriterije prihvatanja i karakteristike proizvoda."),
  Q("8.3.6", "Promjene u razvoju", "Promjene se identifikuju, preispituju, odobravaju i dokumentuju."),
  Q("8.4.1", "Kontrola eksternih dobavljača: opšte", "Kriteriji za ocjenu, izbor, praćenje i ponovnu ocjenu dobavljača."),
  Q("8.4.2", "Vrsta i obim kontrole", "Kako se provjeravaju eksterni procesi, proizvodi i usluge prije upotrebe."),
  Q("8.4.3", "Informacije za dobavljače", "Zahtjevi, odobravanja, kompetencije i verifikacija komunicirani dobavljačima."),
  Q("8.5.1", "Kontrola proizvodnje i pružanja usluga", "Kontrolisani uslovi: uputstva, oprema, praćenje, kvalifikovani ljudi, validacija posebnih procesa."),
  Q("8.5.2", "Identifikacija i sljedivost", "Označavanje izlaza i statusa, sljedivost gdje se traži."),
  Q("8.5.3", "Imovina kupaca i eksternih strana", "Zaštita imovine kupaca, uključujući podatke; izvještavanje o gubitku ili oštećenju."),
  Q("8.5.4", "Očuvanje", "Rukovanje, pakovanje, skladištenje i zaštita izlaza."),
  Q("8.5.5", "Aktivnosti nakon isporuke", "Garancije, servis, reciklaža i povratne informacije kupaca."),
  Q("8.5.6", "Kontrola promjena u proizvodnji", "Neplanirane promjene se preispituju i dokumentuju."),
  Q("8.6", "Puštanje proizvoda i usluga", "Verifikacija prije isporuke, zapis o odobrenju i ko je pustio."),
  Q("8.7", "Kontrola neusaglašenih izlaza", "Označavanje, izdvajanje, korekcija, odobrenje odstupanja i zapisi."),
  Q("9.1.1", "Praćenje i mjerenje: opšte", "Šta se prati, metode, kada i ko analizira rezultate."),
  Q("9.1.2", "Zadovoljstvo kupaca", "Kako se prati percepcija kupaca: ankete, reklamacije, povratne informacije."),
  Q("9.1.3", "Analiza i vrednovanje", "Analiza podataka o procesima, dobavljačima, kupcima i efikasnosti mjera."),
  Q("9.2", "Interni audit", "Program audita, kriteriji, nepristrasni auditori, izvještaji i praćenje nalaza."),
  Q("9.3", "Preispitivanje od strane uprave", "Planirani ulazi, odluke i mjere, zapisi o preispitivanju."),
  Q("10.1", "Poboljšanje: opšte", "Prilike za poboljšanje proizvoda, usluga i QMS-a."),
  Q("10.2", "Neusaglašenost i korektivne mjere", "Reakcija, analiza uzroka, korektivne mjere, provjera efikasnosti i zapisi."),
  Q("10.3", "Stalno poboljšanje", "Pogodnost, adekvatnost i efikasnost QMS-a se stalno poboljšavaju.")
];

/* ---------- NIS2 (Directive (EU) 2022/2555) ---------- */
const N = (id, code, group, title, hint) => ({ id: "n" + id, code, kind: "clause", group, title, hint });
export const NIS2 = [
  N("3a", "Čl. 2–3", "3", "Obuhvat: bitni ili važni subjekt", "Sektor, veličina i djelatnost; da li je firma direktno obuhvaćena ili je dobavljač obuhvaćenog subjekta."),
  N("3b", "Čl. 3(4), 27", "3", "Registracija kod nadležnog organa", "Podaci o subjektu dostavljeni nacionalnom organu gdje zakon to traži; ažuriranje pri promjenama."),
  N("3c", "Čl. 26", "3", "Nadležnost i države djelovanja", "U kojim državama članicama firma pruža usluge i koji organ je nadležan."),
  N("20a", "Čl. 20(1)", "20", "Uprava odobrava mjere i nadzire provedbu", "Organ upravljanja formalno odobrava mjere upravljanja rizicima i prati njihovu provedbu; lična odgovornost uprave."),
  N("20b", "Čl. 20(2)", "20", "Obuka članova uprave", "Članovi uprave redovno prolaze obuku o cyber rizicima i njihovom uticaju na poslovanje."),
  N("20c", "Čl. 20(2)", "20", "Redovna obuka zaposlenih", "Slična obuka se nudi zaposlenima kako bi prepoznali rizike i znali postupke."),
  N("21a1", "Čl. 21(2)(a)", "21", "Politika sigurnosti informacionih sistema", "Odobrena politika s ciljevima, ulogama i periodom preispitivanja."),
  N("21a2", "Čl. 21(2)(a)", "21", "Analiza rizika", "Metodologija, registar rizika, kriteriji prihvatljivosti i plan tretmana, pristup svih opasnosti."),
  N("21b1", "Čl. 21(2)(b)", "21", "Postupak upravljanja incidentima", "Otkrivanje, klasifikacija, reakcija, eskalacija i uloge tima za incidente."),
  N("21b2", "Čl. 21(2)(b)", "21", "Evidencija i analiza incidenata", "Zapisi o incidentima, analiza uzroka i naučene lekcije."),
  N("21c1", "Čl. 21(2)(c)", "21", "Kontinuitet poslovanja", "Analiza uticaja, planovi kontinuiteta i oporavka, testiranje."),
  N("21c2", "Čl. 21(2)(c)", "21", "Backup i oporavak", "Pravila backupa, izolovane kopije, redovni test obnove."),
  N("21c3", "Čl. 21(2)(c)", "21", "Krizno upravljanje", "Krizni tim, komunikacija i odlučivanje u vanrednim situacijama."),
  N("21d1", "Čl. 21(2)(d)", "21", "Sigurnost lanca snabdijevanja", "Popis kritičnih dobavljača i pružalaca usluga, procjena njihovih rizika."),
  N("21d2", "Čl. 21(2)(d), 21(3)", "21", "Sigurnosni zahtjevi u ugovorima s dobavljačima", "Ugovorne obaveze, prijava incidenata, pravo na provjeru; ranjivosti i praksa razvoja dobavljača."),
  N("21e1", "Čl. 21(2)(e)", "21", "Sigurnost pri nabavci, razvoju i održavanju", "Sigurnosni zahtjevi za nove sisteme, siguran razvoj, upravljanje promjenama."),
  N("21e2", "Čl. 21(2)(e)", "21", "Upravljanje ranjivostima i zakrpama", "Skeniranje, prioriteti, rokovi za zakrpe; objavljivanje ranjivosti."),
  N("21f", "Čl. 21(2)(f)", "21", "Procjena efikasnosti mjera", "Pokazatelji, interni auditi, testovi i preispitivanje mjera."),
  N("21g1", "Čl. 21(2)(g)", "21", "Osnovna cyber higijena", "Sigurna konfiguracija, zaštita od malvera, ažuriranja, ograničena administratorska prava."),
  N("21g2", "Čl. 21(2)(g)", "21", "Obuka i svijest o sigurnosti", "Program obuke, phishing vježbe, evidencija učešća."),
  N("21h", "Čl. 21(2)(h)", "21", "Kriptografija i šifrovanje", "Pravila upotrebe šifrovanja podataka u prenosu i mirovanju, upravljanje ključevima."),
  N("21i1", "Čl. 21(2)(i)", "21", "Sigurnost ljudskih resursa", "Provjere pri zapošljavanju, obaveze povjerljivosti, postupak pri odlasku."),
  N("21i2", "Čl. 21(2)(i)", "21", "Kontrola pristupa", "Najmanje privilegije, odobravanje i periodična revizija prava, privilegovani nalozi."),
  N("21i3", "Čl. 21(2)(i)", "21", "Upravljanje imovinom", "Popis sistema, podataka i uređaja s vlasnicima i klasifikacijom."),
  N("21j1", "Čl. 21(2)(j)", "21", "Višefaktorska autentifikacija", "MFA ili kontinuirana autentifikacija za udaljeni i privilegovani pristup."),
  N("21j2", "Čl. 21(2)(j)", "21", "Sigurna i hitna komunikacija", "Zaštićeni glasovni, video i tekstualni kanali, rezervni kanal za hitne slučajeve."),
  N("21k", "Čl. 21(4)", "21", "Korektivne mjere bez odlaganja", "Kada mjere nisu ispunjene, korekcija se provodi bez odlaganja i dokumentuje."),
  N("23a", "Čl. 23(3)", "23", "Kriteriji značajnog incidenta", "Kada je incident značajan: ozbiljan poremećaj usluge, finansijski gubitak ili šteta drugima."),
  N("23b", "Čl. 23(4)(a)", "23", "Rano upozorenje u roku od 24 sata", "Postupak i odgovorna osoba za rano upozorenje nadležnom CSIRT-u ili organu."),
  N("23c", "Čl. 23(4)(b)", "23", "Obavijest o incidentu u roku od 72 sata", "Početna procjena ozbiljnosti, uticaja i pokazatelja kompromitacije."),
  N("23d", "Čl. 23(4)(c)", "23", "Privremeni izvještaj na zahtjev", "Ažuriranje stanja kada to traži CSIRT ili nadležni organ."),
  N("23e", "Čl. 23(4)(d)", "23", "Završni izvještaj u roku od mjesec dana", "Opis, uzrok, primijenjene mjere i prekogranični uticaj."),
  N("23f", "Čl. 23(1)–(2)", "23", "Obavještavanje primalaca usluga", "Obavještavanje korisnika o incidentu i mjerama koje mogu sami poduzeti."),
  N("23g", "Kupac", "23", "Prijava incidenata kupcima po ugovoru", "Rokovi i kontakti za prijavu incidenata kupcima koji traže NIS2 usklađenost od dobavljača.")
];

/* ---------- TISAX (VDA ISA 6, Information Security module, chapters 1–7) ---------- */
const T = (id, title, hint) => ({ id: "t" + id, code: id, kind: "control", group: id.split(".")[0], title, hint });
export const TISAX = [
  T("1.1.1", "Politike informacijske sigurnosti", "Odobrene politike, objavljene zaposlenima i redovno preispitane."),
  T("1.2.1", "Obim i upravljanje ISMS-om", "Definisan obim, ISMS uspostavljen i vođen od uprave."),
  T("1.2.2", "Odgovornosti za informacijsku sigurnost", "Imenovane uloge i odgovornosti, bez sukoba interesa."),
  T("1.2.3", "Sigurnost u projektima", "Sigurnosni zahtjevi identifikovani i praćeni u projektima."),
  T("1.2.4", "Odgovornosti s pružaocima IT usluga", "Jasna podjela odgovornosti s vanjskim pružaocima IT usluga."),
  T("1.3.1", "Identifikacija informacione imovine", "Popis informacija i sistema s vlasnicima."),
  T("1.3.2", "Klasifikacija informacione imovine", "Šema klasifikacije i pravila rukovanja po nivou zaštite."),
  T("1.3.3", "Odobrene vanjske IT usluge", "Samo procijenjene i odobrene cloud i vanjske IT usluge."),
  T("1.3.4", "Odobreni softver", "Samo procijenjen i odobren softver se koristi (novo u ISA 6)."),
  T("1.4.1", "Upravljanje rizicima informacijske sigurnosti", "Metoda procjene rizika, redovna procjena, tretman i vlasnici rizika."),
  T("1.5.1", "Provjera usklađenosti s politikama", "Interni auditi i provjere provedbe politika i zahtjeva."),
  T("1.5.2", "Nezavisni pregled ISMS-a", "Pregled ISMS-a od nezavisne strane u planiranim intervalima."),
  T("1.6.1", "Prijava sigurnosnih događaja", "Kanali i obaveza prijave događaja za zaposlene i partnere."),
  T("1.6.2", "Upravljanje prijavljenim događajima", "Klasifikacija, reakcija, eskalacija i naučene lekcije."),
  T("1.6.3", "Spremnost na krizne situacije", "Planiranje reakcije i oporavka u kriznim situacijama, krizni tim (novo u ISA 6)."),
  T("2.1.1", "Kompetentnost zaposlenih", "Provjera podobnosti i kvalifikacija za osjetljive poslove."),
  T("2.1.2", "Obaveze zaposlenih", "Ugovorne obaveze o sigurnosti i povjerljivosti, i nakon odlaska."),
  T("2.1.3", "Obuka i svijest", "Redovna obuka o sigurnosti za sve zaposlene."),
  T("2.1.4", "Rad na daljinu i mobilni rad", "Pravila i zaštita za rad izvan prostorija firme."),
  T("3.1.1", "Sigurnosne zone", "Zone zaštite prema osjetljivosti, kontrola fizičkog pristupa."),
  T("3.1.3", "Rukovanje pratećom imovinom", "Zaštita opreme i medija tokom korištenja, transporta i uništavanja."),
  T("3.1.4", "Mobilni uređaji i prenosni mediji", "Pravila, šifrovanje i evidencija mobilnih uređaja i medija."),
  T("4.1.1", "Upravljanje sredstvima identifikacije", "Kartice, tokeni i ključevi: izdavanje, evidencija, povrat."),
  T("4.1.2", "Siguran pristup korisnika", "Autentifikacija prema riziku, MFA gdje je potrebno."),
  T("4.1.3", "Korisnički nalozi i podaci za prijavu", "Kreiranje, deaktivacija i zaštita lozinki i naloga."),
  T("4.2.1", "Prava pristupa", "Dodjela po potrebi, odobravanje i periodična revizija prava."),
  T("5.1.1", "Kriptografski postupci", "Pravila šifrovanja i upravljanje ključevima."),
  T("5.1.2", "Zaštita informacija u prenosu", "Sigurni kanali i pravila za razmjenu podataka."),
  T("5.2.1", "Upravljanje promjenama", "Promjene IT sistema se planiraju, testiraju i odobravaju."),
  T("5.2.2", "Razdvajanje razvojnog, testnog i produkcijskog okruženja", "Okruženja odvojena, testni podaci zaštićeni."),
  T("5.2.3", "Zaštita od malvera", "Zaštita krajnjih tačaka i servera, ažurne definicije."),
  T("5.2.4", "Logovi događaja", "Bilježenje, zaštita i analiza logova."),
  T("5.2.5", "Upravljanje ranjivostima", "Identifikacija ranjivosti i zakrpe u definisanim rokovima."),
  T("5.2.6", "Tehničke provjere IT sistema", "Pentest i tehnički auditi, planirani i dokumentovani."),
  T("5.2.7", "Upravljanje mrežom", "Segmentacija, zaštita i nadzor mreže."),
  T("5.2.8", "Kontinuitet IT usluga", "Planiranje kontinuiteta i oporavka kritičnih IT usluga (novo u ISA 6)."),
  T("5.2.9", "Backup i oporavak", "Backup kritičnih podataka i test obnove (novo u ISA 6)."),
  T("5.3.1", "Sigurnost novih i izmijenjenih IT sistema", "Sigurnosni zahtjevi pri nabavci i razvoju sistema."),
  T("5.3.2", "Zahtjevi za mrežne usluge", "Sigurnosni zahtjevi prema pružaocima mrežnih usluga."),
  T("5.3.3", "Povrat i brisanje podataka iz vanjskih usluga", "Povrat i sigurno brisanje informacija na kraju usluge."),
  T("5.3.4", "Zaštita u dijeljenim vanjskim uslugama", "Odvajanje i zaštita podataka u dijeljenim cloud uslugama."),
  T("6.1.1", "Sigurnost kod izvođača i partnera", "Procjena i ugovorni zahtjevi za dobavljače i partnere."),
  T("6.1.2", "Ugovori o povjerljivosti", "NDA s partnerima prije razmjene povjerljivih informacija."),
  T("7.1.1", "Zakonski i ugovorni zahtjevi", "Popis zakona, propisa i ugovornih obaveza i njihovo ispunjavanje."),
  T("7.1.2", "Zaštita ličnih podataka", "Obrada ličnih podataka u skladu s propisima o zaštiti podataka.")
];

export const MORE_GROUPS = {
  iso9001: { clause: { "4": "Kontekst organizacije", "5": "Liderstvo", "6": "Planiranje", "7": "Podrška", "8": "Operativni procesi", "9": "Vrednovanje performansi", "10": "Poboljšanje" } },
  nis2: { clause: { "3": "Obuhvat i registracija", "20": "Upravljanje i odgovornost uprave", "21": "Mjere upravljanja rizicima", "23": "Izvještavanje o incidentima" } },
  tisax: { control: { "1": "Politike i organizacija IS", "2": "Ljudski resursi", "3": "Fizička sigurnost", "4": "Upravljanje identitetima i pristupom", "5": "IT i cyber sigurnost", "6": "Odnosi s dobavljačima", "7": "Usklađenost" } }
};
