/*
 * ISO/IEC 27001:2022 catalogue for Evidenta.
 * Only clause/control numbers and SCE Assurance's own short Bosnian descriptions.
 * The standard's text is copyrighted by ISO and is NOT reproduced here.
 */
const C = (id, title, hint) => ({ id: "c" + id, code: id, kind: "clause", group: id.split(".")[0], title, hint });
const A = (id, title, hint) => ({ id: "a" + id, code: "A." + id, kind: "control", group: id.split(".")[0], title, hint });

export const GROUPS = {
  clause: { "4": "Kontekst", "5": "Liderstvo", "6": "Planiranje", "7": "Podrška", "8": "Operacije", "9": "Vrednovanje performansi", "10": "Poboljšanje" },
  control: { "5": "Organizacijske kontrole", "6": "Kontrole vezane za ljude", "7": "Fizičke kontrole", "8": "Tehnološke kontrole" }
};

export const ISO27001 = [
  C("4.1", "Unutrašnja i vanjska pitanja", "Šta utiče na informacijsku sigurnost firme: tržište, zakoni, tehnologija, klima."),
  C("4.2", "Zainteresovane strane i njihovi zahtjevi", "Kupci, regulator, vlasnici, zaposleni i šta od firme očekuju."),
  C("4.3", "Obim ISMS-a", "Koje lokacije, procesi, sistemi i ljudi su obuhvaćeni, i šta je izuzeto."),
  C("4.4", "Uspostava i održavanje ISMS-a", "Procesi ISMS-a i njihove međusobne veze."),
  C("5.1", "Posvećenost uprave", "Uprava daje resurse, ciljeve i podršku; ISMS je dio poslovanja."),
  C("5.2", "Politika informacijske sigurnosti", "Odobrena politika s ciljevima, objavljena zaposlenima."),
  C("5.3", "Uloge, odgovornosti i ovlaštenja", "Ko vodi ISMS, ko izvještava upravu."),
  C("6.1.1", "Rizici i prilike: opšte", "Planiranje aktivnosti za rizike i prilike ISMS-a."),
  C("6.1.2", "Procjena rizika", "Metodologija, kriteriji prihvatljivosti, identifikacija i analiza rizika."),
  C("6.1.3", "Tretman rizika i Izjava o primjenjivosti", "Plan tretmana, izbor kontrola, SoA, odobrenje vlasnika rizika."),
  C("6.2", "Ciljevi informacijske sigurnosti", "Mjerljivi ciljevi, plan kako ih postići, praćenje."),
  C("6.3", "Planiranje promjena", "Promjene ISMS-a se planiraju i provode kontrolisano."),
  C("7.1", "Resursi", "Ljudi, budžet i alati za ISMS."),
  C("7.2", "Kompetentnost", "Potrebne vještine, obuke i dokazi o kompetentnosti."),
  C("7.3", "Svijest", "Zaposleni znaju politiku, svoju ulogu i posljedice nepoštovanja."),
  C("7.4", "Komunikacija", "Šta, kada, kome i ko komunicira o sigurnosti."),
  C("7.5", "Dokumentovane informacije", "Izrada, odobravanje, verzije, pristup i čuvanje dokumenata i zapisa."),
  C("8.1", "Operativno planiranje i kontrola", "Procesi se izvode po planu, uključujući eksterne procese."),
  C("8.2", "Periodična procjena rizika", "Procjena rizika u planiranim intervalima i pri značajnim promjenama."),
  C("8.3", "Provođenje tretmana rizika", "Plan tretmana se provodi i zapisi se čuvaju."),
  C("9.1", "Praćenje i mjerenje", "Šta se mjeri, kako, kada i ko analizira rezultate."),
  C("9.2", "Interni audit", "Program internog audita, nezavisni auditori, izvještaji."),
  C("9.3", "Preispitivanje od strane uprave", "Uprava redovno preispituje ISMS s propisanim ulazima i izlazima."),
  C("10.1", "Stalno poboljšanje", "ISMS se kontinuirano unapređuje."),
  C("10.2", "Neusaglašenosti i korektivne mjere", "Reakcija na neusaglašenosti, uzroci, korektivne mjere, efikasnost."),

  A("5.1", "Politike informacijske sigurnosti", "Politika i tematske politike, odobrene i preispitane."),
  A("5.2", "Uloge i odgovornosti", "Definisane i dodijeljene sigurnosne uloge."),
  A("5.3", "Razdvajanje dužnosti", "Konfliktne dužnosti su razdvojene."),
  A("5.4", "Odgovornosti rukovodstva", "Rukovodioci traže primjenu pravila od svojih timova."),
  A("5.5", "Kontakt s nadležnim organima", "Ko i kako kontaktira organe (npr. CERT, policija, regulator)."),
  A("5.6", "Kontakt s interesnim grupama", "Stručna udruženja, forumi, izvori informacija."),
  A("5.7", "Obavještajni podaci o prijetnjama", "Prikupljanje i analiza informacija o prijetnjama."),
  A("5.8", "Sigurnost u upravljanju projektima", "Sigurnosni zahtjevi u svakom projektu."),
  A("5.9", "Popis informacija i imovine", "Registar imovine s vlasnicima."),
  A("5.10", "Prihvatljiva upotreba", "Pravila korištenja informacija i opreme."),
  A("5.11", "Povrat imovine", "Vraćanje opreme i podataka pri odlasku."),
  A("5.12", "Klasifikacija informacija", "Nivoi povjerljivosti i kriteriji."),
  A("5.13", "Označavanje informacija", "Oznake u skladu s klasifikacijom."),
  A("5.14", "Prenos informacija", "Pravila za razmjenu informacija: mail, fajlovi, mediji."),
  A("5.15", "Kontrola pristupa", "Pravila pristupa po principu potrebe."),
  A("5.16", "Upravljanje identitetima", "Životni ciklus korisničkih identiteta."),
  A("5.17", "Autentifikacijske informacije", "Lozinke, MFA, dodjela i zaštita."),
  A("5.18", "Prava pristupa", "Dodjela, preispitivanje i ukidanje prava."),
  A("5.19", "Sigurnost u odnosima s dobavljačima", "Rizici dobavljača i pravila saradnje."),
  A("5.20", "Sigurnost u ugovorima s dobavljačima", "Sigurnosni zahtjevi u ugovorima."),
  A("5.21", "Lanac snabdijevanja IKT", "Rizici hardvera, softvera i usluga u lancu."),
  A("5.22", "Praćenje usluga dobavljača", "Redovna provjera i upravljanje promjenama kod dobavljača."),
  A("5.23", "Korištenje cloud usluga", "Nabavka, korištenje i izlazak iz cloud usluga."),
  A("5.24", "Planiranje upravljanja incidentima", "Procedure, uloge i odgovornosti za incidente."),
  A("5.25", "Procjena sigurnosnih događaja", "Da li je događaj incident i kako se klasificira."),
  A("5.26", "Odgovor na incidente", "Postupanje po procedurama."),
  A("5.27", "Učenje iz incidenata", "Analiza i poboljšanja nakon incidenta."),
  A("5.28", "Prikupljanje dokaza", "Čuvanje dokaza o incidentima."),
  A("5.29", "Sigurnost tokom poremećaja", "Održavanje sigurnosti u kriznim situacijama."),
  A("5.30", "IKT spremnost za kontinuitet", "Oporavak IT sistema u zahtijevanim rokovima."),
  A("5.31", "Zakonski i ugovorni zahtjevi", "Registar zahtjeva: zakoni, propisi, ugovori."),
  A("5.32", "Prava intelektualnog vlasništva", "Licence i zaštita autorskih prava."),
  A("5.33", "Zaštita zapisa", "Čuvanje zapisa od gubitka i neovlaštene izmjene."),
  A("5.34", "Privatnost i lični podaci", "Zaštita ličnih podataka (GDPR, zakon BiH)."),
  A("5.35", "Nezavisna provjera sigurnosti", "Periodična nezavisna provjera ISMS-a."),
  A("5.36", "Usklađenost s politikama", "Provjera da li se pravila poštuju."),
  A("5.37", "Dokumentovane operativne procedure", "Procedure za rad s IT sistemima."),
  A("6.1", "Provjera kandidata", "Provjera prije zapošljavanja, srazmjerna riziku."),
  A("6.2", "Uslovi zaposlenja", "Sigurnosne obaveze u ugovorima."),
  A("6.3", "Svijest, edukacija i obuka", "Redovne obuke i kampanje svijesti."),
  A("6.4", "Disciplinski postupak", "Postupak za kršenje pravila."),
  A("6.5", "Obaveze nakon prestanka zaposlenja", "Šta važi i nakon odlaska."),
  A("6.6", "Ugovori o povjerljivosti", "NDA sa zaposlenima i trećim stranama."),
  A("6.7", "Rad na daljinu", "Pravila za rad od kuće i na putu."),
  A("6.8", "Prijava sigurnosnih događaja", "Kako zaposleni prijavljuju događaje."),
  A("7.1", "Fizički perimetri", "Zaštićene zone i granice."),
  A("7.2", "Fizički ulaz", "Kontrola ulaska u prostorije."),
  A("7.3", "Zaštita kancelarija i prostorija", "Fizička zaštita kancelarija i opreme."),
  A("7.4", "Fizički nadzor", "Video nadzor, alarmi, praćenje."),
  A("7.5", "Zaštita od fizičkih i okolišnih prijetnji", "Požar, poplava, nestanak struje."),
  A("7.6", "Rad u zaštićenim zonama", "Pravila za rad u osjetljivim prostorijama."),
  A("7.7", "Čist sto i čist ekran", "Nema dokumenata na stolu, zaključan ekran."),
  A("7.8", "Smještaj i zaštita opreme", "Oprema postavljena i zaštićena od rizika."),
  A("7.9", "Imovina izvan prostorija", "Laptopi i oprema van firme."),
  A("7.10", "Mediji za pohranu", "USB, diskovi: upotreba, prenos, uništavanje."),
  A("7.11", "Prateće instalacije", "Napajanje, UPS, klimatizacija."),
  A("7.12", "Zaštita kablova", "Zaštita energetskih i mrežnih kablova."),
  A("7.13", "Održavanje opreme", "Redovno i kontrolisano održavanje."),
  A("7.14", "Sigurno odlaganje opreme", "Brisanje podataka prije odlaganja ili ponovne upotrebe."),
  A("8.1", "Korisnički uređaji", "Zaštita laptopa i mobilnih uređaja."),
  A("8.2", "Privilegovani pristup", "Admin prava: dodjela, ograničenje, praćenje."),
  A("8.3", "Ograničenje pristupa informacijama", "Pristup u skladu s pravilima."),
  A("8.4", "Pristup izvornom kodu", "Kontrolisan pristup kodu i alatima."),
  A("8.5", "Sigurna autentifikacija", "MFA i sigurne metode prijave."),
  A("8.6", "Upravljanje kapacitetima", "Praćenje i planiranje kapaciteta."),
  A("8.7", "Zaštita od zlonamjernog softvera", "Antivirus/EDR i svijest korisnika."),
  A("8.8", "Upravljanje ranjivostima", "Skeniranje, procjena i zakrpe."),
  A("8.9", "Upravljanje konfiguracijom", "Sigurne i dokumentovane konfiguracije."),
  A("8.10", "Brisanje informacija", "Brisanje podataka kada više nisu potrebni."),
  A("8.11", "Maskiranje podataka", "Maskiranje osjetljivih podataka gdje je potrebno."),
  A("8.12", "Sprečavanje curenja podataka", "DLP mjere za osjetljive podatke."),
  A("8.13", "Backup", "Backup po politici i testiran oporavak."),
  A("8.14", "Redundantnost", "Rezervni kapaciteti za dostupnost."),
  A("8.15", "Logovanje", "Logovi događaja, zaštita i analiza."),
  A("8.16", "Praćenje aktivnosti", "Otkrivanje neuobičajenih aktivnosti u mreži i sistemima."),
  A("8.17", "Sinhronizacija vremena", "Satovi sistema usklađeni s pouzdanim izvorom."),
  A("8.18", "Privilegovani uslužni programi", "Ograničena upotreba moćnih alata."),
  A("8.19", "Instalacija softvera", "Kontrolisana instalacija na produkcijskim sistemima."),
  A("8.20", "Sigurnost mreže", "Zaštita mreža i uređaja."),
  A("8.21", "Sigurnost mrežnih usluga", "Zahtjevi za mrežne usluge i dobavljače."),
  A("8.22", "Segmentacija mreža", "Razdvajanje mreža po namjeni."),
  A("8.23", "Web filtriranje", "Blokiranje zlonamjernih web stranica."),
  A("8.24", "Kriptografija", "Pravila šifrovanja i upravljanje ključevima."),
  A("8.25", "Siguran razvoj", "Sigurnost kroz životni ciklus razvoja."),
  A("8.26", "Sigurnosni zahtjevi aplikacija", "Zahtjevi pri razvoju i nabavci aplikacija."),
  A("8.27", "Sigurna arhitektura sistema", "Principi sigurnog dizajna."),
  A("8.28", "Sigurno kodiranje", "Pravila sigurnog programiranja."),
  A("8.29", "Sigurnosno testiranje", "Testiranje u razvoju i prije prihvatanja."),
  A("8.30", "Eksternalizovani razvoj", "Nadzor nad vanjskim razvojem."),
  A("8.31", "Razdvajanje okruženja", "Razvoj, test i produkcija odvojeni."),
  A("8.32", "Upravljanje promjenama", "Kontrolisane promjene sistema."),
  A("8.33", "Testni podaci", "Zaštita podataka korištenih za testiranje."),
  A("8.34", "Zaštita sistema tokom audit testiranja", "Audit testovi planirani da ne ometaju rad.")
];

import { ISO9001, NIS2, TISAX, MORE_GROUPS } from "./cat-more.js";

/* per standard: groups per kind, labels used in the UI and in reports, whether an SoA applies */
export const STANDARDS = {
  iso27001: { name: "ISO/IEC 27001:2022", items: ISO27001, groups: GROUPS, soa: true,
    kinds: { clause: { tab: "Zahtjevi 4–10", title: "Zahtjevi, poglavlja 4–10", one: "Zahtjev", gp: "" },
             control: { tab: "Aneks A · SoA", title: "Aneks A, teme kontrola", one: "Kontrola Aneksa A", gp: "A." } } },
  iso9001: { name: "ISO 9001:2026", items: ISO9001, groups: MORE_GROUPS.iso9001, soa: false,
    kinds: { clause: { tab: "Zahtjevi 4–10", title: "Zahtjevi, poglavlja 4–10", one: "Zahtjev", gp: "" } } },
  nis2: { name: "NIS2 (Direktiva EU 2022/2555)", items: NIS2, groups: MORE_GROUPS.nis2, soa: false,
    kinds: { clause: { tab: "Zahtjevi NIS2", title: "NIS2, oblasti zahtjeva", one: "Zahtjev NIS2", gp: "Čl. " } } },
  tisax: { name: "TISAX · VDA ISA 6", items: TISAX, groups: MORE_GROUPS.tisax, soa: false,
    kinds: { control: { tab: "VDA ISA 1–7", title: "VDA ISA, poglavlja 1–7", one: "Kontrola VDA ISA", gp: "" } } }
};
